### PR TITLE
Modify Legend Layer Name using setRequestPreCallback()

### PR DESCRIPTION
**Pull request by AkshayHarshe**
This Sample uses  esriRequest.setRequestPreCallback() to call a function and modify the Web_Map_As_JSON request that is sending out to print task.

### CODE REVIEW

**Comment by NoashX** [comment]
I see a couple issues here:

1) I don't see a print option when I run this sample
2) Do not include a link to your locally hosted proxy file (i think there is a generic esri one we can use for samples?)

**Comment by NoashX** [comment]
and update to JS API 3.15?

**Comment by AkshayHarshe** [comment]
Noah, 
1.You need to use your proxy page to see the print option.
2.Changed the proxy url to a generic. still you need to use your own proxy page the generic one esri does not work for different referrer.
3.I have already included a detailed Readme.md file, Please see https://github.com/Esri/developer-support/pull/157/files

If you want I can upload a sample pdf output.
Thanks,
Akshay

**Comment by AkshayHarshe** [comment]
Adding this sample to the pool since all the updates have been made.

**Pull request merged**
