### PR TITLE
Infusion of 4.0.1 functionality: 3D buildings, shadows, atmosphere, a…

### PR DESCRIPTION
**Pull request by NoashX**
Infusion of JavaScript Beta 4.0.1 functionality: 3D buildings, shadows, atmosphere, and Accessor methods in a "fun" mashup sample with buttons. Tried to make a bunch of comments about new features/methods, and there is a dash of console logging.

Is it :sparkling_heart: or :see_no_evil:?

### CODE REVIEW

**Comment by afili** [comment]
Awesome sample! Just wondering about lines 216 and 220. Do we need to assign the elem.value?

**Comment by NoashX** [comment]
good catch @afili, I removed those 2 lines

**Comment by benstoltz** [comment]
Looks good to me! Merging in.

**Comment by NoashX** [comment]
thanks @benstoltz :city_sunrise:

**Pull request merged**
