### PR TITLE
Update a new geocode service

### PR DESCRIPTION
**Pull request by goldenlimit**
Small minor change to make the sample works better, the previous
geocode service is secured

### CODE REVIEW

**Comment by goldenlimit** [comment]
Can anyone test this and merge it? :footprints:

**Comment by gdhakal** [comment]
@goldenlimit I recommend updating Live Preview of the sample in ReadMe file as well.

**Comment by goldenlimit** [comment]
It will be updated once the merge has been completed :smile:

**Comment by gdhakal** [comment]
cool, will merge it! :+1:

**Comment by goldenlimit** [comment]
Thanks @gdhakal and I guess the next thing is to update Esri/gh-pages to sync the update. :bow:

**Comment by nohe427** [comment]
Its been updated @goldenlimit :+1:

**Comment by gdhakal** [comment]
Thanks Alex! @nohe427

**Pull request merged**
