### PR TITLE
Python Sample Added

### PR DESCRIPTION
**Pull request by MKellyEsri**
[Download Feature Layer Attachments](https://geonet.esri.com/docs/DOC-10441-downloading-feature-layer-attachments) script added, along with example output folder and readme.

### CODE REVIEW

**Comment by jgravois** [comment]
very cool! can someone looking for an excuse to get more familiar with our new Python API please review this soon and give @MKellyEsri some feedback?

**Comment by natas333x2** [comment]
I'm looking at it now.  Getting `rename: src too long for Windows` after about 15 downloads.

**Comment by MKellyEsri** [comment]
@natas333x2 Just removed unnecessary output examples as the paths were obviously causing problems

**Comment by MKellyEsri** [comment]
FYI, the script should just run as is with the specified public Feature Layer once you get Jupyter Notebooks up and running

**Comment by natas333x2** [comment]
I'm running it as a notebook but I'm still getting the same error.  What exactly did you change?  I'll try that here.

**Comment by MKellyEsri** [comment]
Ah of course, when you run the script it creates the same folder structure as the example outputs I had in in the Downloads folder. Change the SaveAttachmentsTo variable to something like 'C:\ScriptDownloads' and it should run.

**Comment by MKellyEsri** [comment]
I just made some changes to code - ran on my home computer and fixed a few things I came across. The downloads now get saved to C:\ScriptDownloads by default so once there is write access to that location you shouldn't encounter the same file path limitations.

**Comment by natas333x2** [comment]
Looks good!

**Comment by jgravois** [comment]
@natas333x2 did you mean to _merge_ this?

**Comment by natas333x2** [comment]
Yes, I did.  Did I close it?

**Comment by jgravois** [comment]
yup.  reopening it now

**Pull request merged**
