### PR TITLE
Downloads unanswered GeoNet posts into CSV files from 19 different places

### PR DESCRIPTION
**Pull request by NoashX**
Pulls reports from 19 places (mostly SDK related) on GeoNet about unanswered posts with fewer than 10 replies, then outputs 19 CSV files and sorts each by number of replies.

### CODE REVIEW

**Comment by NoashX** [comment]
And for some reason I've added an update to the main README.md file in this PR as well :confused:
was supposed to resolve issue #144 as a separate PR...

**Comment by jgravois** [comment]
all unique commits in a single branch are compared to the branch the Pull Request is made against.

its usually a good idea to keep a PR focused on a single topic, but also **totally** fine in this case to merge all when someone has been able to confirm that the script produces the expected results and that the documentation already written is sufficient.

just peanut gallery feedback, but seems like the first optimization for the script would be to have it write out a single `.csv` instead of 19. :smile:

**Comment by esoekianto** [comment]
@NoashX this is a pretty neat tool and code but I would argue the need or usage of this sample being here in this repo as it does not show the usage any of our APIs. I might be wrong

**Comment by NoashX** [comment]
Totally valid point @esoekianto. My thinking is that it relates to GeoNet posts, which are very much an Esri thing. But does it use an Esri API or SDK? Not so much. Anyone else think this is valid or not in our repo?

**Comment by NoashX** [comment]
@jgravois the 19 different CSV files were created so people can ignore (or share) certain technologies, but I am open to suggestion, will consider

**Comment by natas333x2** [comment]
@NoashX this is a great script.  I know we started with only AO questions so this will be great for tackling the other technologies.

**Comment by jgravois** [comment]
> the 19 different CSV files were created so people can ignore (or share) certain technologies

it feels sufficient to me that people can manipulate the `PlaceID`s prior to running the script.  if its not cumbersome to look through all the different individual .csv's, fee free to leave it be.

> Anyone else think this is valid or not in our repo?

i see @esoekianto's point, but since the script supports people giving developer support, i don't have a problem with including it here.  if anybody has an alternative suggestion for a appropriate visible place for it to be shared and documented, that'd be fine too.

**Comment by goldenlimit** [comment]
@jgravois this maybe better put in Chatter or SDK F.I.S.H. 
Correctly me if I am wrong. Honestly, when we support on Geonet, it is more spontaneous, free and by interests motivation (even though we add as one of the objectives). The script tool is cool, however it may take much efforts to run this tool versus going to geonet directly to answer those questions you can answer.

**Comment by esoekianto** [comment]
@NoashX @jgravois i think this is a great personal repo for the owner of the scripts

**Comment by NoashX** [comment]
:ok_hand: I think based on @esoekianto and @goldenlimit feedback, I am fine with not merging here and keeping this in my personal repo... thanks @natas333x2 and @jgravois for feedback, which i will incorporate

**Pull request closed without merging**
