### PR TITLE
Fix Report URLs

### PR DESCRIPTION
**Pull request by aOrtego**
This script repairs the erroneous <a> tag's created by the Report
Designer, if hyperlinks are enabled.

### CODE REVIEW

**Comment by jgravois** [comment]
might be nice to link to an article like [this](http://resources.arcgis.com/en/help/main/10.2/index.html#//004v00000002000000) in the README.  i know my desktop skills are rusty, but i had to google 'report designer', because i had no idea what it was.

**Comment by nohe427** [comment]
Works for me.  @aOrtego after you make the adjustments by @jgravois let me know and we can squash the commits and merge them in.

**Comment by aOrtego** [comment]
Should I redo this submission in accordance with the guidelines?

**Comment by nohe427** [comment]
@aOrtego Looks like you're within the guidelines to me.

**Comment by aOrtego** [comment]
'Aight, thanks

**Pull request merged**
