### PR TITLE
Customize Esri Signup dialog box

### PR DESCRIPTION
**Pull request by nagmayasmin**
This sample shows how to customize ESRI Sign up dialog box

### CODE REVIEW

**Comment by NoashX** [comment]
great sample @nagmayasmin! could you add a README.md file to explain what the sample does, and how it can be customized and used by our users?

**Comment by NoashX** [comment]
and maybe update to JS API 3.15

**Comment by NoashX** [comment]
@nagmayasmin and maybe update to JS API 3.15?

**Comment by jgravois** [comment]
@nagmayasmin closing this PR.  if you'd like to incorporate @NoashX's feedback in an additional commit we can reopen.

**Pull request closed without merging**
