### PR TITLE
Add delete users script

### PR DESCRIPTION
**Pull request by kgerrow**
Please make sure this is tested on a test account as it delete's a user and their content.

### CODE REVIEW

**Comment by kgerrow** [comment]
@jgravois 

Let me know if this works. I added three new samples and I guess they all come through on one pull request. I've got way fewer files than the last time.

**Comment by jgravois** [comment]
looking for a Pythonista (or aspiring) to attempt to run @kgerrow's new samples and confirm that the README's provide sufficient explanation regarding their usage and effect.

> Please make sure this is tested on a test account as it delete's a user and their content. 

glad to see that your disclaimer here is just a reiteration of the warning you also included in the doc you wrote.

**Comment by MarieAshley** [comment]
Hey @kgerrow,

Nice script. Tested in a trial organization with four users, two had a role named 'delete'. Script works as documented, only those with the 'delete' role were deleted.

Merging!

**Comment by MarieAshley** [comment]
Also tested 'enabling my esri access' and 'resetting the password' samples in the same trial, those work too!

**Pull request merged**
