### PR TITLE
recover corrupt

### PR DESCRIPTION
**Pull request by AshleyDesktop**
Added ability to recover some corrupt data

### CODE REVIEW

**Comment by AshleyDesktop** [comment]
Second pull request, last one was closed due to merging conflicts.

**Comment by jgravois** [comment]
is anyone available/interested in running @AshleyDesktop 's code and providing feedback as to whether the documentation was clear and the expected outcome was encountered?

**Comment by nohe427** [comment]
I can do this but I may need someone to provide me with sample data offline.

**Comment by jgravois** [comment]
i like the convention of problem/symptoms, but i think providing a little more information for both would make the use-case clearer.

**Comment by AshleyDesktop** [comment]
Thanks! I updated the readme.

**Comment by nohe427** [comment]
Ran the script, it works.

@jgravois Maybe add a little more detail on what you would like to see in the readme?

**Comment by jgravois** [comment]
i agree.

just for the sake of getting more folks involved, lets have @NoashX merge this in and confirm that he was able to pull the latest down from upstream to his local machine afterward.

**Comment by nohe427** [comment]
Before we have @NoashX merge it in, should we get @AshleyDesktop to squash it again?

**Comment by jgravois** [comment]
i feel like i've been too OCD asking people to squash commits everytime prior to merging.
its nice because it makes commit history tidy, but its ultimately not a big deal.

in general, if the contributor who submitted the pull request is interested in trying, its always welcome, but it should not be considered an expectation.

all that said, even though tackling new `git` tasks is always intimidating, trying it **by yourself** can be really rewarding and we can all standby to assist if necessary, so if @AshleyDesktop is game, i say go for it.

**Comment by AshleyDesktop** [comment]
Nohe squashed it

**Comment by jgravois** [comment]
as much as he loves squashing, @nohe427 is officially banned from getting his grubby paws on other people's PRs.  the process is more important than the outcome. :smile:

**Comment by nohe427** [comment]
Darn

**Comment by NoashX** [comment]
verified this script works and the readme is logical, merging #22

**Pull request merged**
