### PR TITLE
Kg sde sdk

### PR DESCRIPTION
**Pull request by natas333x2**
Added a folder to the arcsde-sql dir for the Java SDE SDK.  In here is a dir with a file that inserts simple geometries into feature classes in an SDE geodatabase.

### CODE REVIEW

**Comment by jgravois** [comment]
i really like the idea of providing inline syntax highlighted code samples in all RDBMS READMEs.

ex:
```PLpgSQL
SELECT registration_id, 
		rowid_name, 
		...
FROM table_registry_discovery
ORDER BY registration_id
```
having external `.sql` files is cool too.

**Comment by natas333x2** [comment]
You mean just a readme for the smaller sql  statements?  I like that.
Fewer steps for me.

**Comment by jgravois** [comment]
yeah, i'd vote for inline SQL in the readme everytime.  external `.sql` file optional.

**Comment by natas333x2** [comment]
Sounds good.

**Comment by natas333x2** [comment]
@jgravois -- tried squashing.  May have messed something up.  Sorry.  Let me know if this is broken.

**Comment by natas333x2** [comment]
@jgravois -- I backed my stuff up.  fyi

**Comment by jgravois** [comment]
the squash isn't really that big a deal, but we can't merge this until you resolve the conflicts between your changes and the current state of `master`

**Comment by natas333x2** [comment]
@jgravois  fixed the squashing and conflicts issues.

**Comment by jgravois** [comment]
just a note that i was using `PLpgSQL` as the keyword for syntax highlighting in my own old markdown code snippet in my old PR.  not sure the pros vs. cons of that vs. plain old `sql` but either one is better than what you get with just indentation [here](https://github.com/Esri/developer-support/tree/master/arcsde-sql/postgresql/xy-to-point-cursor)

**Pull request merged**
