### PR TITLE
FolderConnectionManager

### PR DESCRIPTION
**Pull request by aOrtego**
An add-in for Pro which allows user to save/load folder connections from
a text file

### CODE REVIEW

**Comment by jgravois** [comment]
much better!

**Comment by aOrtego** [comment]
Noice! If anyone needs help testin' this out, just lemme know

**Comment by aOrtego** [comment]
Anybody out there wanna take a crack at reviewing this?

**Comment by nohe427** [comment]
View it live link in the read me is a little confusing since the app needs to be downloaded.  Other than that, it works fine.  Merging.

**Comment by nohe427** [comment]
@aOrtego can you update us on what the View it Live link is supposed to do when you return to work?

**Pull request merged**
