### PR TITLE
AppStudio Add Points Sample

### PR DESCRIPTION
**Pull request by nohe427**
This is a preliminary sample.  I am basing it loosly off of something I see in Android.  Hoping to get some cross fork collaboration on this with @gdhakal.  No need to review or merge yet.  When that time comes we will shout-out.

### CODE REVIEW

**Comment by nohe427** [comment]
Current status of sample:

Still needs a lot of :nail_care: but the core features are working.
* Drawing a feature is working - need to update the start path
* Adding a feature is working - need to reset the polygon graphic as to prevent confusion
* Buttons are working - would like to incorporate an undo and delete button but we can incorporate that later.

Shout out to @gdhakal for all the help thus far and looking forward to some continued help in creation of this sample.

**Comment by nohe427** [comment]
This is part 1 from issue #109

**Comment by nohe427** [comment]
I believe this sample is ready.  Can I get @NoashX to test it out for me using the new skills I showed him earlier?

**Comment by NoashX** [comment]
aight @nohe427, let me give it a shot :snail:

**Comment by NoashX** [comment]
strong work @nohe427 :hatching_chick: looks good to me :hatched_chick: merging

**Pull request merged**
