### PR TITLE
Update the html file based on John's suggestion

### PR DESCRIPTION
**Pull request by goldenlimit**
#79 * update the JS and CSS
* update workspace ID doc

### CODE REVIEW

**Comment by marlak** [comment]
Looks good to me :+1: This is what we discussed yesterday with creating the workspace id :smile: 

If you don't mind, may I suggest one simple change to adjust the formatting

**Comment by jgravois** [comment]
I'm not seeing the README fixes.

**Comment by goldenlimit** [comment]
Hmm I am working on it! :dash:

**Comment by goldenlimit** [comment]
@jgravois looks like I have a conflict issue, wonder know how to fix it.

**Comment by jgravois** [comment]
time to learn about resolving merge conflicts :smile:

https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/
http://stackoverflow.com/questions/161813/fix-merge-conflicts-in-git

**Comment by afili** [comment]
thanks @jgravois 

@goldenlimit are you going to work on that today? we can take a stab at it together

**Comment by goldenlimit** [comment]
@afili Sure I will wait you come and dig it 2gether

**Comment by goldenlimit** [comment]
@jgravois me, @afili and @nohe427 fix the issue :sake:

**Comment by jgravois** [comment]
nice work.  the `master` branch on your [fork](https://github.com/goldenlimit/developer-support/) is still way out of date so after this is merged you should get in the habit of synchronizing.
```
git checkout master
git fetch upstream master
git merge upstream/master
git push origin master
```
next time you want to create a feature branch for a new PR, make sure its synchronized (and tracking) as well.
```
git fetch upstream master
git checkout -b newbranch upstream/master
```
rinse and repeat

**Pull request merged**
