### PR TITLE
Java runtime add file based rasters

### PR DESCRIPTION
**Pull request by natas333x2**
Java runtime app that adds rasters matching an extension to a map.

### CODE REVIEW

**Comment by nohe427** [comment]
Can you add a readme @natas333x2 ?

**Comment by natas333x2** [comment]
Yes.  I realized that after adding the sample.

**Comment by natas333x2** [comment]
Readme is in there. :cactus:

**Comment by MarieAshley** [comment]
:+1: I like how references were added at the end of the readme

**Comment by nohe427** [comment]
Tested with a TIF and just getting a black box.  Will test with another image format since I don't see TIF listed as supported

**Comment by natas333x2** [comment]
@nohe427 - Try it now.  The .tif format should be fine as long as the rasters are spatially aware.  I'm pretty sure that's what constitutes a GeoTiff.  I've forgotten just about everything I ever learned about rasters.

**Comment by nohe427** [comment]
Still getting all black screen with this.

Can we chat about this offline perhaps and try adjusting it from there?  It might just be my data.

**Comment by nohe427** [comment]
@nhaney90 resolved this.  We needed to calculate statistics on my raster before we added it.

**Pull request merged**
