### PR TITLE
New script to update the contents of a web map

### PR DESCRIPTION
**Pull request by summelanie**
This python script updates the contents of a web map while maintaining
the existing web map ID. This is a useful workaround to BUG-000085088.

### CODE REVIEW

**Comment by jgravois** [comment]
awesome!  let's have some other new folks jump in to code review, discuss and merge.

**Comment by nohe427** [comment]
arcpy-python/update-webmap-json/README.md
On line 29 add:
```json

on line 59 add:
```

This will add syntax highlighting to your readme for the json.

**Comment by AshleyDesktop** [comment]
Thanks for posting this! A few changes I would make in the readme:

- Under step 4 in Instructions, everything is a bit squished. "true > True false > False null > None 5. On line 96, replace "Replace with JSON, remove the quotes" with your edited JSON 5. Run the script and input your username, password, and web map title"

- Mention that the URLs may be remapped through the ArcGIS Online assistant, but that this script allows us to completely remove the URLs too along with remapping (AGOL assistant does not allow us to remove URLs completely).

ArcGIS Online Assistant
ago-assistant.esri.com/

- Step 3: When viewing the readme (not the raw file) the itemID looked to be treated as html, need to put that back into the URL.

- As this script is meant for someone who does not use python, consider putting in a print statement that prints out the itemID of the webmap, and then instruct the user to plug and chug that ID in the rest url.

- The rest endpoint may not work if the item is not public, user may need to pass a token (or temporarily make the webmap and layers public) to view the JSON.

- Between step 3 and 4 include that the JSON needs to be modified. For example, to delete an entire layer, take out the entire layer dictionary. After replacing the JSON in the script, run the script again.

- Include the bug title.

- I just tested removing a layer completely, script works well! After the various changes to the readme I think this is good to merge.

**Comment by jgravois** [comment]
i just realized that you didn't fork `Esri/developer-support`, but rather created another branch called `UpdateWebmap`, pushed it directly to the upstream repository and submitted your Pull Request from there.

this is totally fine, its just a different workflow than what we discussed in the training last week (and something that only works when you are a contributor to a project, as opposed to sending a patch to someone that you don't know).

@AshleyDesktop if you're up for it, it would be really fun to practice tracking this new branch and laying down another commit with your own suggestions directly on top of what melanie already has.

**Comment by nohe427** [comment]
@AshleyDesktop @summelanie 

Updated the ReadMe.md.  Let me know what you all think or have any questions.  I think there are two items that remain in the checklist above. :octocat:

**Comment by jgravois** [comment]
:+1: for *within branch* collaboration

**Comment by nohe427** [comment]
Changed the script a bit so the web map can be searched for to generate the webMapID in addition to modifying the README to explain how to get a token and append it to the end of a request.

@AshleyDesktop @summelanie let me know what you think

- [ ] Someone may want to test again to make sure I didn't break anything.  If I did, lets just roll it back.

I think that completes the checklist mentioned above.

- [ ] Can someone confirm that everything is completed above?

- [ ] In addition, I think @aOrtego wanted to add in some PEP8 conventions?

**Comment by AshleyDesktop** [comment]
I like it. I'll help document this :)

**Comment by jgravois** [comment]
can anyone else jump in and help code review/merge this PR?

**Comment by AshleyDesktop** [comment]
tested two cases: - updated URL and removed URL. Nice script and updates guys! Merging.

**Pull request merged**
