### PR TITLE
new appStudio sample

### PR DESCRIPTION
**Pull request by marlak**
NOT READY!  :construction: :construction_worker:

Right now we are able to:
1.add a feature using the add button
 get geometry of the mouse click, set the spatial reference define the attributes to use to add the feature, use the addFeature method which adds the features to the table, and applyFeatureEdits  pushed edits to the server
2. Decided to use a Dialog opposed to  a table because there is a bug for tables on devices using QML
 Dialog pops up when we select the feature using the onMousePressed. Used setAttributeValue method to set an attribute fieldname to a given value. We'll use the field selected and text. Then we want to update the feature service table and use the applyFeaturesEdits for the geodatabaseFeatureServiceTable.

Huge Shout out to @nohe427, @andr7430, & @gdhakal  !!!!! Thanks for your help and collaboration Alex, Andrew, and Garima! :facepunch: :ribbon:

### CODE REVIEW

**Comment by marlak** [comment]
Hello :smile: 
Fixed formatting and made some minor tweeks. Does someone want to test it for me?

**Comment by nohe427** [comment]
Hey Marla,

I see 5 HelloWorld.qml files in here.  Are they all required to run the sample?

**Comment by marlak** [comment]
@nohe427 I needed to change a couple things so I  re-added the 'not ready' label. 

I'm in the works of writing the readme. I'll try a rebase and squash for the other commits so we'll only see one.

Thanks!

**Comment by nohe427** [comment]
Hey @marlak 

How is this coming?  My merge fingers are twitching :wink:

**Comment by marlak** [comment]
Hey,
My apologies on the delay. @nohe427, would you mind checking this real quick?

Thanks!

**Pull request merged**
