### PR TITLE
Create merge attachments

### PR DESCRIPTION
**Pull request by MarieAshley**
Python script to merge attachments from two feature classes, a new feature class will be created. Please do not immediately merge pull request. Would greatly appreciate if this was tested with another dataset. This should work for file geodatabase, Oracle 12c, or SQL Server 2012. :sweat_smile:

### CODE REVIEW

**Comment by natas333x2** [comment]
Hey.  This is great.  I'm having trouble with fieldSyntax in a SQL Server gdb.  If I change the cursor to look for Objectid it works fine.

**Comment by MarieAshley** [comment]
Hey @natas333x2! Thanks for testing this! The sample has been updated to allow more variation in the OID field name.

**Comment by jgravois** [comment]
@natas333x2 any more concerns or is this ready to merge?

**Comment by MarieAshley** [comment]
@natas333x2, if this script still fails (I think it should work because it now asks to use fully qualified names), could I have access to the data you are testing with? 

On the other hand, this sample may soon be obsolete. The defect is slated to be fixed in 10.5 and Pro 1.3. See http://pro.arcgis.com/en/pro-app/get-started/whats-new-in-arcgis-pro-1-3.htm:

> A new environment, Maintain Attachments, allows you to enable and disable transfer of attachments to the output tale or feature class. Maintain Attachments is supported by the following tools:
> Append
> Copy
> Copy Features
> Copy Rows
> Merge

With that being said, I'm okay either way to remove this sample or merge it.

**Comment by natas333x2** [comment]
I think it's still relevant for folks who lag on upgrading.  Also, I think in most scenarios it work and my test was a fluke.  I'll go ahead and merge it (sorry for taking so long) and we can iron out the problem I had.

**Pull request merged**
