### PR TITLE
Restructure the python folder.

### PR DESCRIPTION
**Pull request by nohe427**
This aligns with Johns idea on how the python folder should be
structured,

### CODE REVIEW

**Comment by nohe427** [comment]
From Johns comment
```
perhaps the pythonistas want to rearrange the directory structure for desktop python samples, online samples and server admin samples that don't actually import arcpy?
```

**Comment by jgravois** [comment]
happy to merge this, but i don't understand why the feature-branch isn't visible in your [fork](https://github.com/nohe427/developer-support/)

**Comment by nohe427** [comment]
My fork is actually at:
https://github.com/nohe427/developer-support-1/

**Comment by jgravois** [comment]
might be a good idea to blow it away and refork then.

**Comment by nohe427** [comment]
Reforked it

**Comment by jgravois** [comment]
:+1:  thx.

**Pull request merged**
