### PR TITLE
How to Generate a Geodatabase using REST requests and HTTP Client

### PR DESCRIPTION
**Pull request by nhaney90**
I know, I know. It sounds obscure but I promise there is a use case.

### CODE REVIEW

**Comment by jgravois** [comment]
any .NET folks available to review this pull request? @afili? @esoekianto?

**Comment by natas333x2** [comment]
I'm looking at it now and getting an exception trying to open the database to add the layers.
`var gdb = await Geodatabase.OpenAsync(path);`
"Unable to open the database file : "

**Comment by nhaney90** [comment]
@natas333x2 

Yeah, not sure what is going on. It happens to me too. The geodatabase is valid and the file location is correct.

Nicholas

**Comment by nhaney90** [comment]
@natas333x2 

It's some sort of timing issue. If I delay the AddFeatureLayerToMap call it opens the geodatabase without issue. Not sure what the problem is. However the main purpose of this same is to generate the geodatabase, not add the FeatureLayer to the map. So I can either take out that section of code or change the UI to have a button to generate the geodatabase and a second one to add the featurelayer to the map.

**Comment by jgravois** [comment]
> So I can either take out that section of code or change the UI to have a button to generate the geodatabase and a second one to add the featurelayer to the map.

i like the second idea.  i agree that its not the main purpose of the app, but its a bit of a tease not to interact with what you've created.

**Pull request merged**
