### PR TITLE
Added script to arcpy - python

### PR DESCRIPTION
**Pull request by AshleyDesktop**
This script uploads and unpacks tiles from a tile package to ArcGIS Online.

### CODE REVIEW

**Comment by jgravois** [comment]
very cool @AshleyDesktop!  would anyone like to volunteer to run her code and confirm that its self-explanatory and works as expected?

after we're happy with it, if you're up for a completely extra credit exercise, it might also be fun to squash all of your commits down so that the history for this repository is kept a little tidier.  check out the thread between me and @nohe427 in #5 for a little more background.

**Comment by nohe427** [comment]
We just worked out all the squash stuff

**Comment by jgravois** [comment]
i can speak from experience.  next time, save the squashing for last :smile:

either way, good job guys!

**Comment by nohe427** [comment]
Tested with a tpk I spun up right quick.  It works.

**Comment by jgravois** [comment]
:+1:

**Pull request merged**
