### PR TITLE
R stats

### PR DESCRIPTION
**Pull request by aruizga7**
Script to Upload a CSV and create a feature layer using R. If accepted, accurate documentation will be created

### CODE REVIEW

**Comment by jgravois** [comment]
really cool @aruizga7!  it'd be really helpful if you could at least stub out the Windows Command Prompt instructions so that our team can run your sample code prior to merging.

you can find what we're looking for in general [here](https://github.com/Esri/developer-support/issues/18).  in general, this submission looks great!

**Comment by aruizga7** [comment]
I updates it, now the script is ready to be executed using WIndows Command Prompt. Let me know if you have any issue running it. 

I added some instructions in the Readme.

**Comment by jgravois** [comment]
really stoked to have our first contribution from the outside community.
can i get someone to volunteer to try and run this script and provide feedback?

**Comment by AshleyDesktop** [comment]
Hey @aruizga7! Thanks for uploading this. I am getting an error: "There is no package called 'RJSONIO'". I'm on version 3.1.3. Have you run across this before?

**Comment by aruizga7** [comment]
Hi @AshleyDesktop 

Even if you get error installing the package, the script should work and you should have your CSV and a new FeatureLayer in arcGIS online.

Thanks to your note I realized that the package 'RJSONIO' is not necessary and I have removed it from the script. The script is now updated in the repository.

I just tested it with R 3.1.3 and it works for me, let me know if you still have any problem.

**Comment by AshleyDesktop** [comment]
I see it in My Content, thanks! Merging #26

**Pull request merged**
