### PR TITLE
ATL Command :octocat: :neckbeard:

### PR DESCRIPTION
**Pull request by nohe427**

### CODE REVIEW

**Comment by andr7430** [comment]
A few improvements on this doc as it is a very esoteric topic:

### Step 7 ###
You are missing your  
```
importlib("stdole32.tlb"); 
```
You can improve the look with something like this:
```c++
library ATLProject3Lib
{
    importlib("stdole32.tlb"); 
    importlib("stdole2.tlb");
    [
        uuid(1B6F2116-3479-4835-B080-16CEB4076D6C)
    ]
    coclass ZoomIn
    {
       //[default] interface IZoomIn;
        [default] interface IUnknown;
        interface IZoomIn;
    };
};
```

### Step 8 ###
Needs more clarification.
>Farther up the stdafx.h is an import to "C:\Program Files (x86)\ArcGIS\Desktop10.3\com\esriSystemUI.olb". Go ahead and comment that line out.

I am not sure what that means, I did not see any other occurrences of that line

### Step 9 ###
Need a screenshot for implementing the interfaces

### Step 10 ###
Can use some code blocks to improve the look, see step 7

### Step 11 ###
The bitmap part of step 11 could benefit with some screenshot, and point out the fact .PNG don't work

jwjby94vzdd6

:octocat: :koala: :space_invader:

**Comment by andr7430** [comment]
oh and we can do with a video of the process

**Comment by andr7430** [comment]
oh you also had to declare ~CZoomIn(); in the ZoomIn.h file

**Comment by nohe427** [comment]
~CZoomIn() was declared last I checked.  Video might be too long.  I am putting in the last few screenshots now...

**Comment by nohe427** [comment]
Squashed and pushed.  Let me know if I missed anything

**Comment by andr7430** [comment]
looks good :shipit: 
alt text

**Pull request merged**
