### PR TITLE
new esri leaflet angular and requirejs samples

### PR DESCRIPTION
**Pull request by jgravois**
let me know if these aren't self explanatory :sunglasses:

### CODE REVIEW

**Comment by goldenlimit** [comment]
@jgravois looks good, but I wonder for the "demoapp" the renderer looks like not cover the wraparound method

**Comment by jgravois** [comment]
that's not specific to this sample, that's how Esri Leaflet behaves

**Comment by jgravois** [comment]
anyone?

buellert

**Comment by marlak** [comment]
Hey Hey! 

Just a heads up this [link](http://esri.github.io/developer-support/web-leaflet/requirejs/index.html) doesn't work

**Comment by jgravois** [comment]
it will as soon as someone gets around to merging :smile:

**Comment by goldenlimit** [comment]
Can I click the Merge button :jack_o_lantern:

**Pull request merged**
