### PR TITLE
Script to add Server services to a stand-alone Portal

### PR DESCRIPTION
**Pull request by smithers-tdi**
Sample script created to add all unsecured services from an ArcGIS Server to a stand-alone Portal.

### CODE REVIEW

**Comment by jgravois** [comment]
very cool!  someone from the team will take a deeper look and provide feedback shortly.

**Comment by nohe427** [comment]
Hey all,

I am setting it all up and testing now.

**Comment by nohe427** [comment]
image

image

This is awesome.  I was talking to some of our server analysts and they are definitely interested in this tool.  So far it looks to be working for me.  Just waiting to finish a few more tests.

**Comment by nohe427** [comment]
Merged

**Pull request merged**
