### PR TITLE
ArcSDESQLExecute and pyodbc examples

### PR DESCRIPTION
**Pull request by natas333x2**
ArcSDESQLExecute and pyodbc examples

### CODE REVIEW

**Comment by MarieAshley** [comment]
Nice! If you don't have someone in mind already, I'll test this.

**Comment by natas333x2** [comment]
@MarieAshley Please do!  Let me know what you find.

**Comment by MarieAshley** [comment]
Tested, everything works!

**Comment by jgravois** [comment]
nice work guys!

there's no harm in the way you've already done it, but next time a PR like this would make a good candidate for commit squashing, either prior to merge or using GitHub's new handy tools mid-merge.

https://github.com/blog/2141-squash-your-commits
http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by MarieAshley** [comment]
Thanks for the links @jgravois. Neat, squash and merge!

**Pull request merged**
