### PR TITLE
Added example that reads information from local file geodatabases

### PR DESCRIPTION
**Pull request by scMarth**
I created a sample console application that extends ArcObjects in C#. This sample can read from local file geodatabases, and generates a CSV containing information about items contained in those file geodatabases (timestamps, file sizes, categories, paths, hierarchy information)

Usage details and more information is included in the README

### CODE REVIEW

**Comment by jgravois** [comment]
very cool @scMarth! anyone willing/able to review this?

**Comment by natas333x2** [comment]
I'll take it.

**Comment by natas333x2** [comment]
@scMarth Nice script.  I just got a call from a customer wanting the exact same thing.  Very timely.  One question though, in the instructions, for both flags, if I supply only the csv file name I don't get an output.  If I add the full path and file name for the output file it works.  Am I missing something?

**Comment by natas333x2** [comment]
Ignore my last comment.  I was missing something.

**Pull request merged**
