### PR TITLE
4.x folder

### PR DESCRIPTION
**Pull request by afili**
This creates a new 4.x subfolder that will be used for uploading 4.x JavaScript samples.

### CODE REVIEW

**Comment by NoashX** [comment]
thanks @afili should we have a README for this repository? because it's still in beta and a bit different that official released products/samples...

**Comment by afili** [comment]
@NoashX  I am in for that. What about something like "Version 4.0 is in the initial beta phase. Multiple betas are planned before the 4.0 release next year." What else can we mention? 

And maybe a link to https://developers.arcgis.com/javascript/beta/ ?

**Comment by NoashX** [comment]
That sounds good. And maybe a link to the blog for beta 1 that we can update after beta 2 gets released? actually, would it be better to have subfolders for each beta (e.g. beta1, beta2) or just require the beta version to be in the file name?

**Comment by afili** [comment]
I would prefer to have a separate folder for all betas so that we can distinguish beta samples with other samples that will be in the official release in the future. Do you think that we also want to distinguish every single beta with having subfolders for each one? (Actually we can always check the api path in the sample code for that)

**Comment by NoashX** [comment]
Probably just one JS Beta folder will be sufficient for now. Will merge and work on README :+1:

**Pull request merged**
