### PR TITLE
Add REST Java HTTP Sample

### PR DESCRIPTION
**Pull request by phpmaps**
Sample Java client with code to make HTTP requests to do GET, POST and FILE UPLOADS.

### CODE REVIEW

**Comment by jgravois** [comment]
anyone game to review/merge this PR?  i'm trying to convince @phpmaps to stop pushing work directly to `master` and it helps if his pull requests don't just sit idle :smile:

cc/ @esoekianto

**Comment by phpmaps** [comment]
What did I I push to master.  What?

**Comment by jgravois** [comment]
sorry all.  @phpmaps did **not** push any work related to this new sample into `master`.  

i was just mentioning that he did it back in the day and that it is frustrating to submit a pull request that receives no reply or code review.

**Comment by NoashX** [comment]
fyi @nhaney90 @nohe427

**Pull request merged**
