### PR TITLE
Search widget- New sample

### PR DESCRIPTION
**Pull request by gdhakal**

### CODE REVIEW

**Comment by jgravois** [comment]
since this PR includes all the commits from #116 and #177, we should probably review all your work here and close the other two.

next time, if you'd like to isolate the work in individual feature branches completely, you can do this by making sure that each one is tracking `master` explicitly.

```bash
git checkout master
git fetch upstream
git merge upstream/master
git checkout -b myNewBranch upstream/master
```

explicitly declaring `upstream/master` ensures that you don't unintentionally end up tracking whatever branch was checked out previously.  see [git-scm](https://git-scm.com/docs/git-checkout) for more info.

**Comment by gdhakal** [comment]
Thanks @jgravois! I see that I created a new branch from previous branch, not from master. Will make note of it next time. Yup, we can review all 3 samples here and close the other two.

**Comment by nohe427** [comment]
Tested them all using the live samples link.  Works for me.

**Comment by nohe427** [comment]
:+1:

**Pull request merged**
