### PR TITLE
Add check for Compress Log table

### PR DESCRIPTION
**Pull request by kgalliher**

### CODE REVIEW

**Comment by kgalliher** [comment]
@wellsofthewest - Can you review this?  I just added a check for the compress log.

**Comment by kgalliher** [comment]
@wellsofthewest - Hey there.  Can you slap a review on this?  All I did was check if the compress log was empty prior to running the script and adding a message that it will be ignored.  Thanks!

**Comment by kgalliher** [comment]
@jgravois - It looks like @wellsofthewest doesn't have write access.  Can you grant that to him?

**Comment by jgravois** [comment]
I'd love to, but I don't have 🔑 s to any @esri repos anymore.

email [github_admin@esri.com](mailto:github_admin@esri.com) and ask them to add @wellsofthewest to the 'Developer Support' team. (at least I think that's what I named it).

thank you both for continuing to maintain this project!

**Comment by kgalliher** [comment]
@jgravois - can you approve this?  I have a customer I want to share this with but it won't work properly for them without the change in this branch.

**Comment by jgravois** [comment]
since I'm no longer a member of the organization my approval won't look any different than @wellsofthewest's.

have the admin's still not added him to the @Esri Developer Support team? @phpmaps is this something you can help with?

in the meantime, why not just share the file in your `natas333x2-patch-1` branch with the customer?

https://github.com/Esri/developer-support/blob/natas333x2-patch-1/arcsde-sql/sql-server/geodatabase-management/versioning-statistics/versioning-statistics.md

**Comment by lboyd93** [comment]
@kgalliher @jgravois @wellsofthewest I am a maintainer of this repo now since we are getting the Support Analysts back into contributing. I will go ahead and approve of this! Thanks. :)

**Comment by jgravois** [comment]
awesome. thanks for jumping in @lboyd93!

**Pull request merged**
