### PR TITLE
Adding geoenrichment drive time sample

### PR DESCRIPTION
**Pull request by phpmaps**
This sample shows you how to click on an area of interest and return back 5,10 and 15 minute drive times which include Key Global Facts data revealing population statistics .ie total population, total population of females and total population of males.

### CODE REVIEW

**Comment by phpmaps** [comment]
Thanks Ben!

**Comment by phpmaps** [comment]
@benstoltz  @jgravois  do you know what's the workflow for making this sample operational as a Github IO sample?  Aka the live sample page?

https://github.com/Esri/developer-support/tree/master/web-js/geoenrich-drivetimes  see bottom link.  what do I need to do here.

**Comment by NoashX** [comment]
Awesome sample @phpmaps 

From README: "This sample shows you how to click on an area of interest and return back 5,10 and 15 minute drive times which include Key Global Facts data revealing population statistics .ie total population, total population of females and total population of males."

I only see the total population. Is this expected? Or was it supposed to show total, and female, and male populations?

**Comment by phpmaps** [comment]
@NoashX  - thats a good point. The male and female data gets returned but I did not bring that into the popup UI - only did Total Population in the popup UI.   Check the console.log output, which I guess is kinda weak. I to push total males and total females into the popup - it's just a matter of creating new popup objects with label and field name and adding them to the popup template.  That's a really good thing you pointed out.  I will do an update later.  @NoashX @jgravois @benstoltz Can you guys add your twitter handles here in plain text to me?  We had a nice tweet come in regarding developer-support and I want I want to share that with you.

**Pull request merged**
