### PR TITLE
Update leaflet sample

### PR DESCRIPTION
**Pull request by goldenlimit**
Based on https://github.com/Esri/developer-support/issues/129,
Updated a new tilelayer and feel free to check @NoashX @jgravois
@benstoltz :mag: :mag:

### CODE REVIEW

**Comment by benstoltz** [comment]
Hey @goldenlimit With this we aren't using the mapbox api anymore. Let's check with @NoashX and @jgravois to see if we want to keep demonstrating mapbox integration or not.

**Comment by NoashX** [comment]
yeah, I think the point of that specific map was to consume mapbox services, but I will let @jgravois weigh-in here, good sample @goldenlimit and good looking out @benstoltz

**Comment by goldenlimit** [comment]
Okay let me see if I do sth

**Comment by benstoltz** [comment]
Looks good! merging

**Pull request merged**
