### PR TITLE
JavaScript sample

### PR DESCRIPTION
**Pull request by gdhakal**
Added new JavaScript sample

### CODE REVIEW

**Comment by jgravois** [comment]
cool @gdhakal!  it would be helpful if you could clean up the tabbing/formatting (for example at line 100, 130 and 145.  

i think some more inline code comments explaining whats going on would be helpful too, but i wouldn't call it crucial.

**Comment by jgravois** [comment]
:+1: 
looking for a volunteer to run this code, give feedback and merge...

**Comment by afili** [comment]
Tried it at my end. Runs fine and looks good. Think it is ok to merge?

**Comment by jgravois** [comment]
go for it!

**Pull request merged**
