### PR TITLE
1 branch to format them all

### PR DESCRIPTION
**Pull request by marlak**
made separate commits for updating the CSS and JS API versions. In addition to this, ran all these samples through a formatter to make them look pretty :v: :tulip: 

image

Would you like me to squash?

### CODE REVIEW

**Comment by jgravois** [comment]
hah.  a squash would be nice, but not mandatory.

**Comment by marlak** [comment]
:boom: SQUASHED :boom:

**Comment by jgravois** [comment]
looks great.  please sync `gh-pages` now that this is merged.

**Comment by nohe427** [comment]
Helped Sync gh-pages.... :+1: :racehorse: :gb:

**Pull request merged**
