### PR TITLE
ArcObjects

### PR DESCRIPTION
**Pull request by hanhansun**
hanhan's pull request

### CODE REVIEW

**Comment by jgravois** [comment]
@hanhansun these are new samples, correct?  if so, they'll need to placed in their own folders and include README files to explain what they demonstrate and how to run them (more info [here](https://github.com/Esri/developer-support/blob/master/CONTRIBUTING.md#conventions-and-guidelines)).

**Comment by hanhansun** [comment]
I just added README.md for each folder at soap-api.

**Comment by phpmaps** [comment]
Cool.  It might be helpful to add a link to the SOAP UI tool you reference.  
http://www.soapui.org/ .

**Comment by hanhansun** [comment]
Yes. That's right. Let me add it.

**Comment by jgravois** [comment]
i think it'd probably be even more user friendly if you stored the xml directly inline in your readmes so people don't have to toggle back and forth between the source and doc.

ie:
```xml
<yourxml>
</yourxml>
```

can anyone QA the examples here using something like [SoapUI](http://www.soapui.org/)?

@hanhansun did a customer request you put together these samples?  is this a popular thing?

**Comment by nohe427** [comment]
Tested the geocoding one, it works so far...

working on the others...

**Comment by nohe427** [comment]
Tested the others with Hanhan.  Updating Readmes and then merging.

**Pull request merged**
