### PR TITLE
Agol helper

### PR DESCRIPTION
**Pull request by AshleyDesktop**
Created an agol helper class and example classes that inherit from the agol object. May be useful for geocoding, searching for users, searching for groups, or other REST API tasks.

### CODE REVIEW

**Comment by jgravois** [comment]
very cool!

seems crucial that you mention and include a link to [ArcREST](https://github.com/esri/arcrest) (and perhaps even [geoservices-js](https://github.com/esri/geoservices-js)) as examples of other toolkits that provide help with interacting with Esri services.

**Comment by AshleyDesktop** [comment]
Thanks! Included information about the ArcREST in the readme. Left out geoservices-js to focus on python, but I can include that as well.

**Comment by jgravois** [comment]
your call.  anyone (preferably someone new) game for QAing this code so we can get it merged?

**Comment by aOrtego** [comment]
I can help with that if it's OK with the team-- haven't done one of these before

**Comment by nohe427** [comment]
Go for it

**Comment by aOrtego** [comment]
@AshleyDesktop, let's have you update the README as discussed, then I'll merge this. Thanks!

**Pull request merged**
